
package VistaInterfaz;

import Modelos.Datos;

/**
 *
 * @author Charly Cimino
 */
public class Administradores extends javax.swing.JFrame {


    public Administradores(){
        initComponents();
        this.setLocationRelativeTo(null);
        Datos.setAdmins(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblTitulo = new javax.swing.JLabel();
        btnMostarTitulo = new javax.swing.JButton();
        btnOcultarTitulo1 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnVentanaPrueba = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnAdmIrInicio = new javax.swing.JMenuItem();
        btnAdmIrRegistro = new javax.swing.JMenuItem();
        btnAdmIrInicioSesion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jblTitulo.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jblTitulo.setText("Administradores");

        btnMostarTitulo.setBackground(new java.awt.Color(204, 204, 204));
        btnMostarTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMostarTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png"))); // NOI18N
        btnMostarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarTituloActionPerformed(evt);
            }
        });

        btnOcultarTitulo1.setBackground(new java.awt.Color(204, 204, 204));
        btnOcultarTitulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnOcultarTitulo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        btnOcultarTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOcultarTitulo1ActionPerformed(evt);
            }
        });

        btnAtras.setBackground(new java.awt.Color(204, 204, 204));
        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnVentanaPrueba.setBackground(new java.awt.Color(204, 204, 204));
        btnVentanaPrueba.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVentanaPrueba.setForeground(new java.awt.Color(0, 0, 0));
        btnVentanaPrueba.setText("Ver ventana prueba");
        btnVentanaPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentanaPruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jblTitulo)
                        .addGap(265, 265, 265))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVentanaPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMostarTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnOcultarTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnAtras)
                .addGap(151, 151, 151)
                .addComponent(jblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostarTitulo)
                    .addComponent(btnOcultarTitulo1))
                .addGap(48, 48, 48)
                .addComponent(btnVentanaPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        jMenu1.setText("Inicio");

        btnAdmIrInicio.setText("Ir a Inicio");
        btnAdmIrInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmIrInicioActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmIrInicio);

        btnAdmIrRegistro.setText("Ir a registro");
        btnAdmIrRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmIrRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmIrRegistro);

        btnAdmIrInicioSesion.setText("Ir a inicio sesion");
        btnAdmIrInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmIrInicioSesionActionPerformed(evt);
            }
        });
        jMenu1.add(btnAdmIrInicioSesion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem2.setText("jMenuItem2");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("jMenu4");

        jMenuItem4.setText("jMenuItem4");
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdmIrInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmIrInicioActionPerformed
        Datos.getStart().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmIrInicioActionPerformed

    private void btnAdmIrInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmIrInicioSesionActionPerformed
        Datos.getLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmIrInicioSesionActionPerformed

    private void btnAdmIrRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmIrRegistroActionPerformed
        Datos.getRegistro().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdmIrRegistroActionPerformed

    private void btnMostarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarTituloActionPerformed
        jblTitulo.setVisible(true);
    }//GEN-LAST:event_btnMostarTituloActionPerformed

    private void btnOcultarTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOcultarTitulo1ActionPerformed
        jblTitulo.setVisible(false);
    }//GEN-LAST:event_btnOcultarTitulo1ActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        Datos.getLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnVentanaPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentanaPruebaActionPerformed
        Datos.getVentanaPrueba().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentanaPruebaActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAdmIrInicio;
    private javax.swing.JMenuItem btnAdmIrInicioSesion;
    private javax.swing.JMenuItem btnAdmIrRegistro;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnMostarTitulo;
    private javax.swing.JButton btnOcultarTitulo1;
    private javax.swing.JButton btnVentanaPrueba;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jblTitulo;
    // End of variables declaration//GEN-END:variables
}
