package VistaInterfaz;

import Modelos.Datos;
import Modelos.Personas;
import java.awt.Color;
import javax.swing.ImageIcon;


public class Administradores extends javax.swing.JFrame {

    int indice = Datos.indiceLogin;
    boolean verPassword = false;

    public Administradores() {
        initComponents();
        this.setLocationRelativeTo(null);
        jblVentanaActual.setText("Dashboard");
        try {
            if (Datos.getAtributeInIndex(indice, "nombre").equals("")) {
                jblNombrePerfil.setText("Usuario");
            } else {
                jblNombrePerfil.setText(Datos.getAtributeInIndex(indice, "nombre")+" "+Datos.getAtributeInIndex(indice, "apellido"));
            }

        } catch (Exception e) {
            jblNombrePerfil.setText("Usuario");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        jblPerfil = new javax.swing.JLabel();
        jblNombrePerfil = new javax.swing.JLabel();
        panelConfig = new javax.swing.JPanel();
        jblConfig = new javax.swing.JLabel();
        jblFondoPerfil = new javax.swing.JLabel();
        panelDashboard = new javax.swing.JPanel();
        jblDashboard = new javax.swing.JLabel();
        panelDepositar = new javax.swing.JPanel();
        jblDepositar = new javax.swing.JLabel();
        iconBarra = new javax.swing.JLabel();
        jblVentanaActual = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jblBarra = new javax.swing.JLabel();
        tbdPizarra = new javax.swing.JTabbedPane();
        panelDashboardOp = new javax.swing.JPanel();
        jblVer = new javax.swing.JLabel();
        panelInfoSorteo = new javax.swing.JPanel();
        jblMasInfo = new javax.swing.JLabel();
        jblMarco1 = new javax.swing.JLabel();
        panelDepositarOp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelSorteo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelConfigOp = new javax.swing.JPanel();
        panelEditDatos = new javax.swing.JPanel();
        jblPassword = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jblCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jblTelefono = new javax.swing.JLabel();
        psdPassword = new javax.swing.JPasswordField();
        txtTelefono = new javax.swing.JTextField();
        panelVerPass = new javax.swing.JPanel();
        jblVerPass = new javax.swing.JLabel();
        panelEditar = new javax.swing.JPanel();
        jblEditar = new javax.swing.JLabel();
        panelGuardar = new javax.swing.JPanel();
        jblGuardar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(252, 247, 215));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(247, 240, 194));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfilNegro128px.png"))); // NOI18N
        panel.add(jblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 130, 130));

        jblNombrePerfil.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jblNombrePerfil.setForeground(new java.awt.Color(51, 51, 51));
        jblNombrePerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombrePerfil.setText("Nombre");
        panel.add(jblNombrePerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 300, -1));

        panelConfig.setBackground(new java.awt.Color(204, 212, 152));
        panelConfig.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblConfig.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/config32px.png"))); // NOI18N
        jblConfig.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblConfigMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblConfigMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblConfigMouseExited(evt);
            }
        });
        panelConfig.add(jblConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        panel.add(panelConfig, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 50, 50));

        jblFondoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFondoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gradientePanel.jpg"))); // NOI18N
        panel.add(jblFondoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 200));

        panelDashboard.setBackground(new java.awt.Color(252, 247, 215));
        panelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblDashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDashboard.setForeground(new java.awt.Color(102, 102, 102));
        jblDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu32px.png"))); // NOI18N
        jblDashboard.setText(" Dashboard   ");
        jblDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblDashboardMouseExited(evt);
            }
        });
        panelDashboard.add(jblDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panel.add(panelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 300, 60));

        panelDepositar.setBackground(new java.awt.Color(252, 247, 215));
        panelDepositar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblDepositar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblDepositar.setForeground(new java.awt.Color(102, 102, 102));
        jblDepositar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblDepositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/depositar32px.png"))); // NOI18N
        jblDepositar.setText(" Depositar     ");
        jblDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblDepositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblDepositarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblDepositarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblDepositarMouseExited(evt);
            }
        });
        panelDepositar.add(jblDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        panel.add(panelDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 300, 60));

        background.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        iconBarra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo32px.png"))); // NOI18N
        background.add(iconBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, -1, 60));

        jblVentanaActual.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblVentanaActual.setForeground(new java.awt.Color(51, 51, 51));
        jblVentanaActual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ubicacion32px.png"))); // NOI18N
        jblVentanaActual.setText("Dashboard");
        background.add(jblVentanaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 400, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("BNBUU");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 120, 60));

        jblBarra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BarraBambuColor.png"))); // NOI18N
        background.add(jblBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 790, 60));

        tbdPizarra.setBackground(new java.awt.Color(252, 247, 215));
        tbdPizarra.setForeground(new java.awt.Color(204, 204, 204));

        panelDashboardOp.setBackground(new java.awt.Color(255, 255, 255));
        panelDashboardOp.setForeground(new java.awt.Color(204, 204, 204));
        panelDashboardOp.setToolTipText("");
        panelDashboardOp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png"))); // NOI18N
        panelDashboardOp.add(jblVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        panelInfoSorteo.setBackground(new java.awt.Color(252, 247, 215));
        panelInfoSorteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblMasInfo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jblMasInfo.setForeground(new java.awt.Color(102, 102, 102));
        jblMasInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblMasInfo.setText("Mas info");
        jblMasInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblMasInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblMasInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblMasInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblMasInfoMouseExited(evt);
            }
        });
        panelInfoSorteo.add(jblMasInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        panelDashboardOp.add(panelInfoSorteo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 100, 40));

        jblMarco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MarcoAnunciosBorde.png"))); // NOI18N
        panelDashboardOp.add(jblMarco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        tbdPizarra.addTab("Dashboard", panelDashboardOp);

        panelDepositarOp.setBackground(new java.awt.Color(255, 255, 255));
        panelDepositarOp.setForeground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Ingrese los siguientes datos:");

        javax.swing.GroupLayout panelDepositarOpLayout = new javax.swing.GroupLayout(panelDepositarOp);
        panelDepositarOp.setLayout(panelDepositarOpLayout);
        panelDepositarOpLayout.setHorizontalGroup(
            panelDepositarOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositarOpLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        panelDepositarOpLayout.setVerticalGroup(
            panelDepositarOpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDepositarOpLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(601, Short.MAX_VALUE))
        );

        tbdPizarra.addTab("Depositar", panelDepositarOp);

        panelSorteo.setBackground(new java.awt.Color(255, 255, 255));
        panelSorteo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("sorteo");
        panelSorteo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 270, -1));

        tbdPizarra.addTab("Sorteo", panelSorteo);

        panelConfigOp.setBackground(new java.awt.Color(255, 255, 255));
        panelConfigOp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEditDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelEditDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblPassword.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jblPassword.setText("PASSWORD");
        panelEditDatos.add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 580, -1));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        panelEditDatos.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 750, 10));

        jblName.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblName.setForeground(new java.awt.Color(51, 51, 51));
        jblName.setText("USUARIO");
        panelEditDatos.add(jblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, -1));

        txtName.setBackground(new java.awt.Color(255, 255, 255));
        txtName.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtName.setForeground(new java.awt.Color(204, 204, 204));
        txtName.setText("dzsfsafv");
        txtName.setBorder(null);
        panelEditDatos.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 580, 40));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        panelEditDatos.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 750, 10));

        jblApellido.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblApellido.setForeground(new java.awt.Color(51, 51, 51));
        jblApellido.setText("APELLIDO");
        panelEditDatos.add(jblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 580, -1));

        txtApellido.setBackground(new java.awt.Color(255, 255, 255));
        txtApellido.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.setText("dzsfsafv");
        txtApellido.setBorder(null);
        panelEditDatos.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 580, 40));

        jSeparator3.setForeground(new java.awt.Color(51, 51, 51));
        panelEditDatos.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 750, 10));

        jblCedula.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblCedula.setForeground(new java.awt.Color(51, 51, 51));
        jblCedula.setText("CEDULA");
        panelEditDatos.add(jblCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 580, -1));

        txtCedula.setBackground(new java.awt.Color(255, 255, 255));
        txtCedula.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(204, 204, 204));
        txtCedula.setText("dzsfsafv");
        txtCedula.setBorder(null);
        panelEditDatos.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 580, 40));

        jSeparator4.setForeground(new java.awt.Color(51, 51, 51));
        panelEditDatos.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 750, 10));

        jblTelefono.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblTelefono.setForeground(new java.awt.Color(51, 51, 51));
        jblTelefono.setText("TELEFONO");
        panelEditDatos.add(jblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 580, -1));

        psdPassword.setBackground(new java.awt.Color(255, 255, 255));
        psdPassword.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        psdPassword.setForeground(new java.awt.Color(204, 204, 204));
        psdPassword.setText("jPasswordField1");
        psdPassword.setBorder(null);
        panelEditDatos.add(psdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 580, 40));

        txtTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setText("dzsfsafv");
        txtTelefono.setBorder(null);
        panelEditDatos.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 580, 40));

        panelVerPass.setBackground(new java.awt.Color(255, 255, 255));
        panelVerPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerPass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        jblVerPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblVerPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerPassMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerPassMouseExited(evt);
            }
        });
        panelVerPass.add(jblVerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        panelEditDatos.add(panelVerPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 40, 40));

        panelConfigOp.add(panelEditDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 570));

        panelEditar.setBackground(new java.awt.Color(204, 212, 152));
        panelEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblEditar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblEditar.setForeground(new java.awt.Color(102, 102, 102));
        jblEditar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblEditar.setText("EDITAR");
        jblEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblEditarMouseExited(evt);
            }
        });
        panelEditar.add(jblEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        panelConfigOp.add(panelEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 130, 60));

        panelGuardar.setBackground(new java.awt.Color(204, 212, 152));
        panelGuardar.setForeground(new java.awt.Color(51, 51, 51));
        panelGuardar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblGuardar.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jblGuardar.setForeground(new java.awt.Color(102, 102, 102));
        jblGuardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblGuardar.setText("GUARDAR");
        jblGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblGuardarMouseExited(evt);
            }
        });
        panelGuardar.add(jblGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 60));

        panelConfigOp.add(panelGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 130, 60));

        tbdPizarra.addTab("tab4", panelConfigOp);

        background.add(tbdPizarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 790, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jblDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseEntered
        panelDashboard.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblDashboardMouseEntered

    private void jblDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseExited
        panelDashboard.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblDashboardMouseExited

    private void jblDepositarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseEntered
        panelDepositar.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblDepositarMouseEntered

    private void jblDepositarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseExited
        panelDepositar.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblDepositarMouseExited

    private void jblMasInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblMasInfoMouseEntered
        panelInfoSorteo.setBackground(new Color(247, 240, 194));
    }//GEN-LAST:event_jblMasInfoMouseEntered

    private void jblMasInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblMasInfoMouseExited
        panelInfoSorteo.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblMasInfoMouseExited

    private void jblDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDashboardMouseClicked
        tbdPizarra.setSelectedIndex(0);
        jblVentanaActual.setText("Dashboard");
    }//GEN-LAST:event_jblDashboardMouseClicked

    private void jblDepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblDepositarMouseClicked
        tbdPizarra.setSelectedIndex(1);
        jblVentanaActual.setText("Depositar");
    }//GEN-LAST:event_jblDepositarMouseClicked

    private void jblMasInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblMasInfoMouseClicked
        tbdPizarra.setSelectedIndex(2);
        jblVentanaActual.setText("Sorteo");
    }//GEN-LAST:event_jblMasInfoMouseClicked

    private void jblConfigMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseEntered
        panelConfig.setBackground(new Color(215, 227, 141));
    }//GEN-LAST:event_jblConfigMouseEntered

    private void jblConfigMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseExited
        panelConfig.setBackground(new Color(204, 212, 152));
    }//GEN-LAST:event_jblConfigMouseExited

    private void jblConfigMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfigMouseClicked
        tbdPizarra.setSelectedIndex(3);
        jblVentanaActual.setText("Configuracion");
        try {
            txtName.setText(Datos.getAtributeInIndex(indice, "nombre"));
            txtApellido.setText(Datos.getAtributeInIndex(indice, "apellido"));
            txtCedula.setText(Datos.getAtributeInIndex(indice, "cedula"));
            txtTelefono.setText(Datos.getAtributeInIndex(indice, "telefono"));
            psdPassword.setText(Datos.getAtributeInIndex(indice, "password"));
        } catch (Exception e) {
            txtName.setText("Usuario");
            txtApellido.setText("Apellido");
            txtCedula.setText("Cedula");
            txtTelefono.setText("Telefono");
            psdPassword.setText("Password");
        }

        txtName.setForeground(new Color(204, 204, 204));
        txtApellido.setForeground(new Color(204, 204, 204));
        txtCedula.setForeground(new Color(204, 204, 204));
        txtTelefono.setForeground(new Color(204, 204, 204));
        psdPassword.setForeground(new Color(204, 204, 204));
        txtName.setEditable(false);
        txtApellido.setEditable(false);
        txtCedula.setEditable(false);
        txtTelefono.setEditable(false);
        psdPassword.setEditable(false);
    }//GEN-LAST:event_jblConfigMouseClicked

    private void jblVerPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPassMouseEntered
        panelVerPass.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblVerPassMouseEntered

    private void jblVerPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPassMouseExited
        panelVerPass.setBackground(Color.white);
    }//GEN-LAST:event_jblVerPassMouseExited

    private void jblVerPassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPassMouseClicked

        if (verPassword == false) {
            verPassword = true;
            jblVerPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png")));
            psdPassword.setEchoChar((char) 0);
        } else {
            verPassword = false;
            jblVerPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png")));
            psdPassword.setEchoChar('*');
        }

    }//GEN-LAST:event_jblVerPassMouseClicked

    private void jblEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEditarMouseEntered
        panelEditar.setBackground(new Color(228, 237, 170));
        jblEditar.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jblEditarMouseEntered

    private void jblEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEditarMouseExited
        panelEditar.setBackground(new Color(204, 212, 152));
        jblEditar.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jblEditarMouseExited

    private void jblEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEditarMouseClicked
        txtName.setEditable(true);
        txtApellido.setEditable(true);
        txtCedula.setEditable(true);
        txtTelefono.setEditable(true);
        psdPassword.setEditable(true);
        txtName.setForeground(new Color(102, 102, 102));
        txtApellido.setForeground(new Color(102, 102, 102));
        txtCedula.setForeground(new Color(102, 102, 102));
        txtTelefono.setForeground(new Color(102, 102, 102));
        psdPassword.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jblEditarMouseClicked

    private void jblGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblGuardarMouseEntered
        panelGuardar.setBackground(new Color(228, 237, 170));
        jblGuardar.setForeground(new Color(51, 51, 51));
    }//GEN-LAST:event_jblGuardarMouseEntered

    private void jblGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblGuardarMouseExited
        panelGuardar.setBackground(new Color(204, 212, 152));
        jblGuardar.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_jblGuardarMouseExited

    private void jblGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblGuardarMouseClicked
        Datos.getListaPersonas().get(indice).setNombre(txtName.getText());
        Datos.getListaPersonas().get(indice).setApellido(txtApellido.getText());
        Datos.getListaPersonas().get(indice).setCedula(txtCedula.getText());
        Datos.getListaPersonas().get(indice).setTelefono(txtTelefono.getText());
        Datos.getListaPersonas().get(indice).setPassword(String.valueOf(psdPassword.getPassword()));
        jblNombrePerfil.setText(Datos.getAtributeInIndex(indice, "nombre")+" "+Datos.getAtributeInIndex(indice, "apellido"));
        txtName.setForeground(new Color(204, 204, 204));
        txtApellido.setForeground(new Color(204, 204, 204));
        txtCedula.setForeground(new Color(204, 204, 204));
        txtTelefono.setForeground(new Color(204, 204, 204));
        psdPassword.setForeground(new Color(204, 204, 204));
        txtName.setEditable(false);
        txtApellido.setEditable(false);
        txtCedula.setEditable(false);
        txtTelefono.setEditable(false);
        psdPassword.setEditable(false);
    }//GEN-LAST:event_jblGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administradores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel iconBarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jblApellido;
    private javax.swing.JLabel jblBarra;
    private javax.swing.JLabel jblCedula;
    private javax.swing.JLabel jblConfig;
    private javax.swing.JLabel jblDashboard;
    private javax.swing.JLabel jblDepositar;
    private javax.swing.JLabel jblEditar;
    private javax.swing.JLabel jblFondoPerfil;
    private javax.swing.JLabel jblGuardar;
    private javax.swing.JLabel jblMarco1;
    private javax.swing.JLabel jblMasInfo;
    private javax.swing.JLabel jblName;
    private javax.swing.JLabel jblNombrePerfil;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblPerfil;
    private javax.swing.JLabel jblTelefono;
    private javax.swing.JLabel jblVentanaActual;
    private javax.swing.JLabel jblVer;
    private javax.swing.JLabel jblVerPass;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panelConfig;
    private javax.swing.JPanel panelConfigOp;
    private javax.swing.JPanel panelDashboard;
    private javax.swing.JPanel panelDashboardOp;
    private javax.swing.JPanel panelDepositar;
    private javax.swing.JPanel panelDepositarOp;
    private javax.swing.JPanel panelEditDatos;
    private javax.swing.JPanel panelEditar;
    private javax.swing.JPanel panelGuardar;
    private javax.swing.JPanel panelInfoSorteo;
    private javax.swing.JPanel panelSorteo;
    private javax.swing.JPanel panelVerPass;
    private javax.swing.JPasswordField psdPassword;
    private javax.swing.JTabbedPane tbdPizarra;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
