package VistaInterfaz;

import Modelos.Datos;
import Modelos.Personas;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Charly Cimino
 */
public class Inicio extends javax.swing.JFrame {

    boolean verPassword = false;
    private int index;

    DefaultTableModel modelo;

    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        //Inicio
        panelAtrasInicio.setVisible(false);
        //Inicio Sesion
        txtsPorDefecto();

        //Registarse
        modelo = new DefaultTableModel();
        this.tablaRegistro.setModel(modelo);

        this.modelo.addColumn("Nombre");
        this.modelo.addColumn("Apellido");
        this.modelo.addColumn("Telefono");
        this.modelo.addColumn("Cedula");
        this.modelo.addColumn("Password");
    }

    public int getIndex() {
        return index;
    }

    public void txtsPorDefecto() {
        txtUsuario.setText("Ingrese su usuario");
        psdPassword.setText("**********");
    }
    
    public void txtsRegistroPorDefecto(){
        txtUsuarioOF.setText("Ingrese su usuario");
        txtApellidoOF.setText("Ingrese sus apellidos");
        txtTelefonoOF.setText("Ingrese su telefono");
        txtCedulaOF.setText("Ingrese su cedula");
        psdPasswordOF.setText("Ingrese su password");
    }
    
    public void txtsSetPredeterminatedText(String is) {
        if (!(txtUsuarioOF.getText().equals("Ingrese su usuario")) && !(txtUsuarioOF.getText().equals("")) && !is.equals("usuario")) {
            txtUsuarioOF.setForeground(new Color(153, 153, 153));
        } else {
            if (txtUsuarioOF.getText().equals("")) {
                txtUsuarioOF.setText("Ingrese su usuario");
            }
            txtUsuarioOF.setForeground(new Color(153, 153, 153));
        }

        if (!(txtApellidoOF.getText().equals("Ingrese sus apellidos")) && !(txtApellidoOF.getText().equals("")) && !is.equals("apellidos")) {
            txtApellidoOF.setForeground(new Color(153, 153, 153));
        } else {
            if (txtApellidoOF.getText().equals("")) {
                txtApellidoOF.setText("Ingrese sus apellidos");
            }
            txtApellidoOF.setForeground(new Color(153, 153, 153));
        }

        if (!(txtCedulaOF.getText().equals("Ingrese su cedula")) && !(txtCedulaOF.getText().equals("")) && !is.equals("cedula")) {
            txtCedulaOF.setForeground(new Color(153, 153, 153));
        } else {
            if (txtCedulaOF.getText().equals("")) {
                txtCedulaOF.setText("Ingrese su cedula");
            }
            txtCedulaOF.setForeground(new Color(153, 153, 153));
        }

        if (!(txtTelefonoOF.getText().equals("Ingrese su telefono")) && !(txtTelefonoOF.getText().equals("")) && !is.equals("telefono")) {
            txtTelefonoOF.setForeground(new Color(153, 153, 153));
        } else {
            if (txtTelefonoOF.getText().equals("")) {
                txtTelefonoOF.setText("Ingrese su telefono");
            }
            txtTelefonoOF.setForeground(new Color(153, 153, 153));
        }

        if (!(String.valueOf(psdPasswordOF.getPassword()).equals("Ingrese su password")) && !(String.valueOf(psdPasswordOF.getPassword()).equals("")) && !is.equals("password")) {
            psdPasswordOF.setForeground(new Color(153, 153, 153));
        } else {
            if (String.valueOf(psdPasswordOF.getPassword()).equals("")) {
                psdPasswordOF.setText("Ingrese su password");
            }
            psdPasswordOF.setForeground(new Color(153, 153, 153));
        }

        if (!is.equals("txts por defecto")) {
            cbRol.setForeground(new Color(153, 153, 153));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundInicio = new javax.swing.JPanel();
        panelAtrasInicio = new javax.swing.JPanel();
        jblAtrasInicio = new javax.swing.JLabel();
        lblBarraBanner = new javax.swing.JLabel();
        tbpVentanas = new javax.swing.JTabbedPane();
        panelInicio = new javax.swing.JPanel();
        jblLogo1 = new javax.swing.JLabel();
        jblFrase1 = new javax.swing.JLabel();
        jblNombreBanco1 = new javax.swing.JLabel();
        lblFondoInicio = new javax.swing.JLabel();
        jblNombreYLogo = new javax.swing.JLabel();
        panelInicioSesion = new javax.swing.JPanel();
        jblLogin = new javax.swing.JLabel();
        panelRegistroUsuario = new javax.swing.JPanel();
        jblRegistro = new javax.swing.JLabel();
        jblMensaje = new javax.swing.JLabel();
        jblTitulo = new javax.swing.JLabel();
        panelRegistroPrueba = new javax.swing.JPanel();
        backgroundRegistro = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jblNombre = new javax.swing.JLabel();
        jblApellido = new javax.swing.JLabel();
        jblTelefono = new javax.swing.JLabel();
        jblCedula = new javax.swing.JLabel();
        jblPassword2 = new javax.swing.JLabel();
        jblRol = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        psdPasswordRegistro = new javax.swing.JPasswordField();
        cbxRol = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRegistro = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        panelLogin = new javax.swing.JPanel();
        backgroundLogin = new javax.swing.JPanel();
        jblLogo = new javax.swing.JLabel();
        jblNombreBanco = new javax.swing.JLabel();
        jblFrase = new javax.swing.JLabel();
        jblFondoPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jblPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jblUsuario = new javax.swing.JLabel();
        psdPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        panelEntrar = new javax.swing.JPanel();
        jblEntrar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jblIniciarSesion = new javax.swing.JLabel();
        panelnAtras = new javax.swing.JPanel();
        panelVerPassword = new javax.swing.JPanel();
        jblVerPassword = new javax.swing.JLabel();
        panelRegistro = new javax.swing.JPanel();
        jblLogo2 = new javax.swing.JLabel();
        jblNombreBanco2 = new javax.swing.JLabel();
        jblFrase2 = new javax.swing.JLabel();
        jblFondoRegistro = new javax.swing.JLabel();
        jblRolOF = new javax.swing.JLabel();
        sep2 = new javax.swing.JSeparator();
        jblUsuarioOF = new javax.swing.JLabel();
        txtUsuarioOF = new javax.swing.JTextField();
        sep1 = new javax.swing.JSeparator();
        jblApellidoOF = new javax.swing.JLabel();
        txtApellidoOF = new javax.swing.JTextField();
        sep3 = new javax.swing.JSeparator();
        jblCedulaOF = new javax.swing.JLabel();
        txtCedulaOF = new javax.swing.JTextField();
        sep4 = new javax.swing.JSeparator();
        jblTelefonoOF = new javax.swing.JLabel();
        txtTelefonoOF = new javax.swing.JTextField();
        psdPasswordOF = new javax.swing.JPasswordField();
        sep5 = new javax.swing.JSeparator();
        jblPasswordOF = new javax.swing.JLabel();
        cbRol = new javax.swing.JComboBox<>();
        jblBancoLogo = new javax.swing.JLabel();
        jblIniciarSesion1 = new javax.swing.JLabel();
        panelGuardarOF = new javax.swing.JPanel();
        jblGuardarOF = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundInicio.setBackground(new java.awt.Color(255, 255, 255));
        backgroundInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAtrasInicio.setBackground(new java.awt.Color(252, 247, 215));
        panelAtrasInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblAtrasInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAtrasInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jblAtrasInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblAtrasInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAtrasInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblAtrasInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblAtrasInicioMouseExited(evt);
            }
        });
        panelAtrasInicio.add(jblAtrasInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        backgroundInicio.add(panelAtrasInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        lblBarraBanner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio/BarraInicio.png"))); // NOI18N
        backgroundInicio.add(lblBarraBanner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 50));

        tbpVentanas.setBackground(new java.awt.Color(255, 255, 255));
        tbpVentanas.setForeground(new java.awt.Color(204, 204, 204));

        panelInicio.setBackground(new java.awt.Color(255, 255, 255));
        panelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblLogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo128px.png"))); // NOI18N
        panelInicio.add(jblLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 390, 130));

        jblFrase1.setBackground(new java.awt.Color(0, 0, 0));
        jblFrase1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFrase1.setForeground(new java.awt.Color(51, 51, 51));
        jblFrase1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFrase1.setText("Deje que su dinero brote con nosotros");
        panelInicio.add(jblFrase1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 390, -1));

        jblNombreBanco1.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jblNombreBanco1.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreBanco1.setText("BNBUU");
        panelInicio.add(jblNombreBanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 390, -1));

        lblFondoInicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio/fondoInicioBN.png"))); // NOI18N
        panelInicio.add(lblFondoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, -10, 390, 720));

        jblNombreYLogo.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jblNombreYLogo.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreYLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo64px.png"))); // NOI18N
        jblNombreYLogo.setText("BNBUU");
        panelInicio.add(jblNombreYLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 205, -1));

        panelInicioSesion.setBackground(new java.awt.Color(95, 87, 74));
        panelInicioSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblLogin.setForeground(new java.awt.Color(250, 246, 235));
        jblLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogin.setText("INICIAR SESION");
        jblLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblLoginMouseExited(evt);
            }
        });
        panelInicioSesion.add(jblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        panelInicio.add(panelInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 390, 70));

        panelRegistroUsuario.setBackground(new java.awt.Color(95, 87, 74));
        panelRegistroUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblRegistro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblRegistro.setForeground(new java.awt.Color(250, 246, 235));
        jblRegistro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblRegistro.setText("REGISTRARSE");
        jblRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblRegistroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblRegistroMouseExited(evt);
            }
        });
        panelRegistroUsuario.add(jblRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 70));

        panelInicio.add(panelRegistroUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 390, 70));

        jblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblMensaje.setForeground(new java.awt.Color(51, 51, 51));
        jblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblMensaje.setText("Si no estas registrado te invitamos a registrarte!");
        panelInicio.add(jblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 670, -1));

        jblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        jblTitulo.setText("INICIO");
        panelInicio.add(jblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        tbpVentanas.addTab("Inicio", panelInicio);

        panelRegistroPrueba.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistroPrueba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundRegistro.setBackground(new java.awt.Color(255, 255, 255));

        jblNombre.setText("Nombre");

        jblApellido.setText("Apellido");

        jblTelefono.setText("Telefono");

        jblCedula.setText("Cedula");

        jblPassword2.setText("Password");

        jblRol.setText("Rol");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        cbxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jblRol, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psdPasswordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblPassword2)
                    .addComponent(psdPasswordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jblRol)
                    .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tablaRegistro);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        btnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout backgroundRegistroLayout = new javax.swing.GroupLayout(backgroundRegistro);
        backgroundRegistro.setLayout(backgroundRegistroLayout);
        backgroundRegistroLayout.setHorizontalGroup(
            backgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundRegistroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(backgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundRegistroLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        backgroundRegistroLayout.setVerticalGroup(
            backgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundRegistroLayout.createSequentialGroup()
                .addGroup(backgroundRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundRegistroLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundRegistroLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        panelRegistroPrueba.add(backgroundRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tbpVentanas.addTab("Registro", panelRegistroPrueba);

        panelLogin.setBackground(new java.awt.Color(255, 255, 255));
        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundLogin.setBackground(new java.awt.Color(255, 255, 255));
        backgroundLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo128px.png"))); // NOI18N
        backgroundLogin.add(jblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 390, 130));

        jblNombreBanco.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jblNombreBanco.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreBanco.setText("BNBUU");
        backgroundLogin.add(jblNombreBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 390, -1));

        jblFrase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFrase.setForeground(new java.awt.Color(51, 51, 51));
        jblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFrase.setText("Deje que su dinero brote con nosotros");
        backgroundLogin.add(jblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 390, -1));

        jblFondoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        backgroundLogin.add(jblFondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, -10, 390, 690));

        jLabel1.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo64px.png"))); // NOI18N
        jLabel1.setText("BNBUU");
        backgroundLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 205, -1));

        jblPassword.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jblPassword.setText("PASSWORD");
        backgroundLogin.add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        backgroundLogin.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 420, 50));

        jblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jblUsuario.setText("USUARIO");
        backgroundLogin.add(jblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        psdPassword.setBackground(new java.awt.Color(255, 255, 255));
        psdPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        psdPassword.setForeground(new java.awt.Color(204, 204, 204));
        psdPassword.setText("**********");
        psdPassword.setBorder(null);
        psdPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psdPasswordMousePressed(evt);
            }
        });
        backgroundLogin.add(psdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 380, 60));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        backgroundLogin.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 530, 10));

        panelEntrar.setBackground(new java.awt.Color(92, 88, 29));

        jblEntrar.setBackground(new java.awt.Color(92, 88, 29));
        jblEntrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblEntrar.setText("ENTRAR");
        jblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backgroundLogin.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        backgroundLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 530, 10));

        jblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jblIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        jblIniciarSesion.setText("INICIAR SESION");
        backgroundLogin.add(jblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelnAtras.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelnAtrasLayout = new javax.swing.GroupLayout(panelnAtras);
        panelnAtras.setLayout(panelnAtrasLayout);
        panelnAtrasLayout.setHorizontalGroup(
            panelnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        panelnAtrasLayout.setVerticalGroup(
            panelnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        backgroundLogin.add(panelnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));

        panelVerPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelVerPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        jblVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseExited(evt);
            }
        });
        panelVerPassword.add(jblVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        backgroundLogin.add(panelVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 40, 40));

        panelLogin.add(backgroundLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 668));

        tbpVentanas.addTab("Login", panelLogin);

        panelRegistro.setBackground(new java.awt.Color(255, 255, 255));
        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblLogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo128px.png"))); // NOI18N
        panelRegistro.add(jblLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 390, 130));

        jblNombreBanco2.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jblNombreBanco2.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreBanco2.setText("BNBUU");
        panelRegistro.add(jblNombreBanco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 420, 390, -1));

        jblFrase2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFrase2.setForeground(new java.awt.Color(51, 51, 51));
        jblFrase2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFrase2.setText("Deje que su dinero brote con nosotros");
        panelRegistro.add(jblFrase2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 390, -1));

        jblFondoRegistro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jblFondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Inicio/fondoRegistroPanel.png"))); // NOI18N
        panelRegistro.add(jblFondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, -40, 390, 720));

        jblRolOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblRolOF.setForeground(new java.awt.Color(51, 51, 51));
        jblRolOF.setText("ROL");
        panelRegistro.add(jblRolOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 130, 30));

        sep2.setForeground(new java.awt.Color(102, 102, 102));
        panelRegistro.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 620, 10));

        jblUsuarioOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblUsuarioOF.setForeground(new java.awt.Color(51, 51, 51));
        jblUsuarioOF.setText("NOMBRE");
        panelRegistro.add(jblUsuarioOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 130, 30));

        txtUsuarioOF.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioOF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtUsuarioOF.setForeground(new java.awt.Color(153, 153, 153));
        txtUsuarioOF.setText("Ingrese su usuario");
        txtUsuarioOF.setBorder(null);
        txtUsuarioOF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioOFMousePressed(evt);
            }
        });
        panelRegistro.add(txtUsuarioOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 460, 50));

        sep1.setForeground(new java.awt.Color(102, 102, 102));
        panelRegistro.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 620, 10));

        jblApellidoOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblApellidoOF.setForeground(new java.awt.Color(51, 51, 51));
        jblApellidoOF.setText("APELLIDOS");
        panelRegistro.add(jblApellidoOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 30));

        txtApellidoOF.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoOF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtApellidoOF.setForeground(new java.awt.Color(153, 153, 153));
        txtApellidoOF.setText("Ingrese sus apellidos");
        txtApellidoOF.setBorder(null);
        txtApellidoOF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoOFMousePressed(evt);
            }
        });
        panelRegistro.add(txtApellidoOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 460, 50));

        sep3.setForeground(new java.awt.Color(102, 102, 102));
        panelRegistro.add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 620, 10));

        jblCedulaOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblCedulaOF.setForeground(new java.awt.Color(51, 51, 51));
        jblCedulaOF.setText("CEDULA");
        panelRegistro.add(jblCedulaOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, 30));

        txtCedulaOF.setBackground(new java.awt.Color(255, 255, 255));
        txtCedulaOF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtCedulaOF.setForeground(new java.awt.Color(153, 153, 153));
        txtCedulaOF.setText("Ingrese su cedula");
        txtCedulaOF.setBorder(null);
        txtCedulaOF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCedulaOFMousePressed(evt);
            }
        });
        panelRegistro.add(txtCedulaOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 460, 50));

        sep4.setForeground(new java.awt.Color(102, 102, 102));
        panelRegistro.add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 620, 10));

        jblTelefonoOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblTelefonoOF.setForeground(new java.awt.Color(51, 51, 51));
        jblTelefonoOF.setText("TELEFONO");
        panelRegistro.add(jblTelefonoOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 140, 30));

        txtTelefonoOF.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoOF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTelefonoOF.setForeground(new java.awt.Color(153, 153, 153));
        txtTelefonoOF.setText("Ingrese su telefono");
        txtTelefonoOF.setBorder(null);
        txtTelefonoOF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoOFMousePressed(evt);
            }
        });
        panelRegistro.add(txtTelefonoOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 460, 50));

        psdPasswordOF.setBackground(new java.awt.Color(255, 255, 255));
        psdPasswordOF.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        psdPasswordOF.setForeground(new java.awt.Color(153, 153, 153));
        psdPasswordOF.setText("Ingrese su password");
        psdPasswordOF.setBorder(null);
        psdPasswordOF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psdPasswordOFMousePressed(evt);
            }
        });
        panelRegistro.add(psdPasswordOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 370, 50));

        sep5.setForeground(new java.awt.Color(102, 102, 102));
        panelRegistro.add(sep5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 620, 10));

        jblPasswordOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblPasswordOF.setForeground(new java.awt.Color(51, 51, 51));
        jblPasswordOF.setText("PASSWORD");
        panelRegistro.add(jblPasswordOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 30));

        cbRol.setBackground(new java.awt.Color(255, 255, 255));
        cbRol.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbRol.setForeground(new java.awt.Color(153, 153, 153));
        cbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario", "Administrador" }));
        cbRol.setBorder(null);
        cbRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbRolMousePressed(evt);
            }
        });
        panelRegistro.add(cbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 170, 50));

        jblBancoLogo.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jblBancoLogo.setForeground(new java.awt.Color(51, 51, 51));
        jblBancoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo64px.png"))); // NOI18N
        jblBancoLogo.setText("BNBUU");
        panelRegistro.add(jblBancoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 205, -1));

        jblIniciarSesion1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jblIniciarSesion1.setForeground(new java.awt.Color(51, 51, 51));
        jblIniciarSesion1.setText("REGISTRO");
        panelRegistro.add(jblIniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        panelGuardarOF.setBackground(new java.awt.Color(92, 88, 29));
        panelGuardarOF.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblGuardarOF.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblGuardarOF.setForeground(new java.awt.Color(255, 255, 255));
        jblGuardarOF.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblGuardarOF.setText("GUARDAR");
        jblGuardarOF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblGuardarOFMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblGuardarOFMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblGuardarOFMouseExited(evt);
            }
        });
        panelGuardarOF.add(jblGuardarOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 60));

        panelRegistro.add(panelGuardarOF, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 150, 60));

        tbpVentanas.addTab("tab4", panelRegistro);

        backgroundInicio.add(tbpVentanas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed

        String psd = String.valueOf(psdPassword.getPassword());
        if (txtUsuario.getText().equals("Ingrese su usuario")) {
            txtUsuario.setText("");
        }
        txtUsuario.setForeground(Color.black);
        if (psd.equals("")) {
            psdPassword.setText("**********");
        } else {
            psdPassword.setText(psd);
        }
        psdPassword.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void psdPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdPasswordMousePressed

        String user = txtUsuario.getText();
        if (String.valueOf(psdPassword.getPassword()).equals("**********")) {
            psdPassword.setText("");
        }
        psdPassword.setForeground(Color.black);
        if (user.equals("")) {
            txtUsuario.setText("Ingrese su usuario");
        } else {
            txtUsuario.setText(user);
        }
        txtUsuario.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_psdPasswordMousePressed

    private void jblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseClicked
        String usuario = txtUsuario.getText();
        String password = String.valueOf(psdPassword.getPassword());
        int PersonasRegistradas = Datos.listaPersonas.size();

        txtUsuario.setText("");
        psdPassword.setText("");

        boolean CredencialesIguales = false;
        int rol = 0;

        try {
            if (PersonasRegistradas > 0) {

                for (Personas p : Datos.listaPersonas) {
                    if (p.getNombre().equals(usuario) && p.getPassword().equals(password)) {
                        CredencialesIguales = true;
                        index = Datos.listaPersonas.indexOf(p);
                        Datos.setIndiceLogin(index);
                        rol = p.getRol();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay usuarios registrados");
                txtsPorDefecto();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, intentalo de nuevo");
            txtsPorDefecto();
        }

        if (CredencialesIguales == true) {
            JOptionPane.showMessageDialog(null, "Datos correctos");
            switch (rol) {
                case 0 -> {
                    Datos.setIndiceLogin(index);
                    this.dispose();
                    Administradores admins = new Administradores();
                    admins.setVisible(true);
                }
                case 1 -> {
                    Datos.setIndiceLogin(index);
                    this.dispose();
                    Administradores admins = new Administradores();
                    admins.setVisible(true);
                }
            }
        } else if (PersonasRegistradas > 0 && CredencialesIguales == false) {
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
            txtsPorDefecto();
        }
    }//GEN-LAST:event_jblEntrarMouseClicked

    private void jblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseEntered
        panelEntrar.setBackground(new Color(153, 145, 86));
        jblEntrar.setForeground(Color.black);
    }//GEN-LAST:event_jblEntrarMouseEntered

    private void jblEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseExited
        panelEntrar.setBackground(new Color(92, 88, 29));
        jblEntrar.setForeground(Color.white);
    }//GEN-LAST:event_jblEntrarMouseExited

    private void jblVerPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseClicked
        if (verPassword == false) {
            verPassword = true;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png")));
            psdPassword.setEchoChar((char) 0);
        } else {
            verPassword = false;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png")));
            psdPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jblVerPasswordMouseClicked

    private void jblVerPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseEntered
        panelVerPassword.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblVerPasswordMouseEntered

    private void jblVerPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseExited
        panelVerPassword.setBackground(Color.white);
    }//GEN-LAST:event_jblVerPasswordMouseExited

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char k = evt.getKeyChar();

        if (!(Character.isDigit(k))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {

            modelo.addRow(new Object[]{txtNombre.getText(), txtApellido.getText(), txtTelefono.getText(), txtCedula.getText(), psdPasswordRegistro.getPassword().toString()});

            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String telefono = txtTelefono.getText();
            String cedula = txtCedula.getText();
            String password = String.valueOf(psdPasswordRegistro.getPassword());
            int rol = cbxRol.getSelectedIndex();

            Personas p = new Personas(nombre, apellido, telefono, cedula, password, rol);
            Datos.listaPersonas.add(p);

            this.txtNombre.setText("");
            this.txtApellido.setText("");
            this.txtTelefono.setText("");
            this.txtCedula.setText("");
            this.psdPasswordRegistro.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jblRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRegistroMouseEntered
        panelRegistroUsuario.setBackground(new Color(153, 145, 86));
        jblRegistro.setForeground(Color.black);
    }//GEN-LAST:event_jblRegistroMouseEntered

    private void jblRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRegistroMouseExited
        panelRegistroUsuario.setBackground(new Color(92, 88, 29));
        jblRegistro.setForeground(Color.white);
    }//GEN-LAST:event_jblRegistroMouseExited

    private void jblRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblRegistroMouseClicked
        tbpVentanas.setSelectedIndex(3);
        for (Personas p : Datos.getListaPersonas()) {
            modelo.addRow(new Object[]{p.getNombre(), p.getApellido(), p.getTelefono(), p.getCedula(), p.getPassword()}
            );
        }

        txtsRegistroPorDefecto();
        panelAtrasInicio.setVisible(true);
    }//GEN-LAST:event_jblRegistroMouseClicked

    private void jblLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblLoginMouseEntered
        panelInicioSesion.setBackground(new Color(153, 145, 86));
        jblLogin.setForeground(Color.black);
    }//GEN-LAST:event_jblLoginMouseEntered

    private void jblLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblLoginMouseExited
        panelInicioSesion.setBackground(new Color(92, 88, 29));
        jblLogin.setForeground(Color.white);
    }//GEN-LAST:event_jblLoginMouseExited

    private void jblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblLoginMouseClicked
        tbpVentanas.setSelectedIndex(2);
        txtsPorDefecto();
        panelAtrasInicio.setVisible(true);
    }//GEN-LAST:event_jblLoginMouseClicked

    private void txtUsuarioOFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioOFMousePressed
        txtsSetPredeterminatedText("usuario");
        if (txtUsuarioOF.getText().equals("Ingrese su usuario")) {
            txtUsuarioOF.setText("");
        }
        txtUsuarioOF.setForeground(new Color(102, 102, 102));

    }//GEN-LAST:event_txtUsuarioOFMousePressed

    private void txtApellidoOFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoOFMousePressed
        txtsSetPredeterminatedText("apellidos");
        if (txtApellidoOF.getText().equals("Ingrese sus apellidos")) {
            txtApellidoOF.setText("");
        }
        txtApellidoOF.setForeground(new Color(102, 102, 102));

    }//GEN-LAST:event_txtApellidoOFMousePressed

    private void txtCedulaOFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCedulaOFMousePressed
        txtsSetPredeterminatedText("cedula");
        if (txtCedulaOF.getText().equals("Ingrese su cedula")) {
            txtCedulaOF.setText("");
        }
        txtCedulaOF.setForeground(new Color(102, 102, 102));

    }//GEN-LAST:event_txtCedulaOFMousePressed

    private void txtTelefonoOFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoOFMousePressed
        txtsSetPredeterminatedText("telefono");
        if (txtTelefonoOF.getText().equals("Ingrese su telefono")) {
            txtTelefonoOF.setText("");
        }
        txtTelefonoOF.setForeground(new Color(102, 102, 102));

    }//GEN-LAST:event_txtTelefonoOFMousePressed

    private void psdPasswordOFMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdPasswordOFMousePressed
        txtsSetPredeterminatedText("password");
        if (String.valueOf(psdPasswordOF.getPassword()).equals("Ingrese su password")) {
            psdPasswordOF.setText("");
        }
        psdPasswordOF.setForeground(new Color(102, 102, 102));

    }//GEN-LAST:event_psdPasswordOFMousePressed

    private void cbRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbRolMousePressed

        cbRol.setForeground(new Color(102, 102, 102));
    }//GEN-LAST:event_cbRolMousePressed

    private void jblGuardarOFMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblGuardarOFMouseEntered
        panelGuardarOF.setBackground(new Color(153, 145, 86));
        jblGuardarOF.setForeground(Color.black);
    }//GEN-LAST:event_jblGuardarOFMouseEntered

    private void jblGuardarOFMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblGuardarOFMouseExited
        panelGuardarOF.setBackground(new Color(92, 88, 29));
        jblGuardarOF.setForeground(Color.white);
    }//GEN-LAST:event_jblGuardarOFMouseExited

    private void jblGuardarOFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblGuardarOFMouseClicked
        try {

            //modelo.addRow(new Object[]
            //{txtNombre.getText(),txtApellido.getText(),txtTelefono.getText(),txtCedula.getText(), psdPasswordRegistro.getPassword().toString()});
            String nombre = txtUsuarioOF.getText();
            String apellido = txtApellidoOF.getText();
            String telefono = txtTelefonoOF.getText();
            String cedula = txtCedulaOF.getText();
            String password = String.valueOf(psdPasswordOF.getPassword());
            int rol = cbRol.getSelectedIndex();

            if(nombre.trim().equals("") || apellido.trim().equals("") || telefono.trim().equals("") || cedula.trim().equals("") || password.trim().equals("")){
                JOptionPane.showMessageDialog(null, "Error, espacios sin llenar");
                txtsRegistroPorDefecto();
            }else{
                if(nombre.equals("Ingrese su usuario") || apellido.equals("Ingrese sus apellidos") || telefono.equals("Ingrese su telefono") 
                   || cedula.equals("Ingrese su cedula") || password.equals("Ingrese su password")){
                    
                   JOptionPane.showMessageDialog(null, "Error, debes ingresar tus datos");  
                   txtsRegistroPorDefecto();
                }else{
                    Personas p = new Personas(nombre, apellido, telefono, cedula, password, rol);
                    Datos.listaPersonas.add(p);

                    JOptionPane.showMessageDialog(null, "Datos guardados");
                    tbpVentanas.setSelectedIndex(0);
                    panelAtrasInicio.setVisible(false);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error");
        }
    }//GEN-LAST:event_jblGuardarOFMouseClicked

    private void jblAtrasInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasInicioMouseEntered
        panelAtrasInicio.setBackground(new Color(232, 225, 182));
    }//GEN-LAST:event_jblAtrasInicioMouseEntered

    private void jblAtrasInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasInicioMouseExited
        panelAtrasInicio.setBackground(new Color(252, 247, 215));
    }//GEN-LAST:event_jblAtrasInicioMouseExited

    private void jblAtrasInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasInicioMouseClicked
        tbpVentanas.setSelectedIndex(0);
        panelAtrasInicio.setVisible(false);
    }//GEN-LAST:event_jblAtrasInicioMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundInicio;
    private javax.swing.JPanel backgroundLogin;
    private javax.swing.JPanel backgroundRegistro;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbRol;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblApellido;
    private javax.swing.JLabel jblApellidoOF;
    private javax.swing.JLabel jblAtrasInicio;
    private javax.swing.JLabel jblBancoLogo;
    private javax.swing.JLabel jblCedula;
    private javax.swing.JLabel jblCedulaOF;
    private javax.swing.JLabel jblEntrar;
    private javax.swing.JLabel jblFondoPanel;
    private javax.swing.JLabel jblFondoRegistro;
    private javax.swing.JLabel jblFrase;
    private javax.swing.JLabel jblFrase1;
    private javax.swing.JLabel jblFrase2;
    private javax.swing.JLabel jblGuardarOF;
    private javax.swing.JLabel jblIniciarSesion;
    private javax.swing.JLabel jblIniciarSesion1;
    private javax.swing.JLabel jblLogin;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel jblLogo1;
    private javax.swing.JLabel jblLogo2;
    private javax.swing.JLabel jblMensaje;
    private javax.swing.JLabel jblNombre;
    private javax.swing.JLabel jblNombreBanco;
    private javax.swing.JLabel jblNombreBanco1;
    private javax.swing.JLabel jblNombreBanco2;
    private javax.swing.JLabel jblNombreYLogo;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblPassword2;
    private javax.swing.JLabel jblPasswordOF;
    private javax.swing.JLabel jblRegistro;
    private javax.swing.JLabel jblRol;
    private javax.swing.JLabel jblRolOF;
    private javax.swing.JLabel jblTelefono;
    private javax.swing.JLabel jblTelefonoOF;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel jblUsuario;
    private javax.swing.JLabel jblUsuarioOF;
    private javax.swing.JLabel jblVerPassword;
    private javax.swing.JLabel lblBarraBanner;
    private javax.swing.JLabel lblFondoInicio;
    private javax.swing.JPanel panelAtrasInicio;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelGuardarOF;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelInicioSesion;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JPanel panelRegistroPrueba;
    private javax.swing.JPanel panelRegistroUsuario;
    private javax.swing.JPanel panelVerPassword;
    private javax.swing.JPanel panelnAtras;
    private javax.swing.JPasswordField psdPassword;
    private javax.swing.JPasswordField psdPasswordOF;
    private javax.swing.JPasswordField psdPasswordRegistro;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JSeparator sep5;
    private javax.swing.JTable tablaRegistro;
    private javax.swing.JTabbedPane tbpVentanas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtApellidoOF;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaOF;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoOF;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtUsuarioOF;
    // End of variables declaration//GEN-END:variables
}
