
package VistaInterfaz;

import Modelos.Datos;
import Modelos.Personas;
import java.awt.Color;
import javax.swing.JOptionPane;


public class Loggin extends javax.swing.JFrame {

    private int index;
    boolean verPassword = false;

    public Loggin() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtsPorDefecto();
    }
    
    public void txtsPorDefecto(){
        txtUsuario.setText("Ingrese su usuario");
        psdPassword.setText("**********");
    }

    public int getIndex(){
        return index;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgound = new javax.swing.JPanel();
        jblLogo = new javax.swing.JLabel();
        jblNombreBanco = new javax.swing.JLabel();
        jblFrase = new javax.swing.JLabel();
        jblFondoPanel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jblPassword = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jblUsuario = new javax.swing.JLabel();
        psdPassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        panelEntrar = new javax.swing.JPanel();
        jblEntrar = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jblIniciarSesion = new javax.swing.JLabel();
        panelnAtras = new javax.swing.JPanel();
        jblAtras = new javax.swing.JLabel();
        panelVerPassword = new javax.swing.JPanel();
        jblVerPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        backgound.setBackground(new java.awt.Color(255, 255, 255));
        backgound.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                backgoundFocusGained(evt);
            }
        });
        backgound.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo128px.png"))); // NOI18N
        backgound.add(jblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 390, 130));

        jblNombreBanco.setFont(new java.awt.Font("STSong", 1, 36)); // NOI18N
        jblNombreBanco.setForeground(new java.awt.Color(51, 51, 51));
        jblNombreBanco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNombreBanco.setText("BNBUU");
        backgound.add(jblNombreBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 390, -1));

        jblFrase.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblFrase.setForeground(new java.awt.Color(51, 51, 51));
        jblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFrase.setText("Deje que su dinero brote con nosotros");
        backgound.add(jblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 460, 390, -1));

        jblFondoPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.jpg"))); // NOI18N
        backgound.add(jblFondoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, -10, 390, 690));

        jLabel1.setFont(new java.awt.Font("STSong", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bambuLogo64px.png"))); // NOI18N
        jLabel1.setText("BNBUU");
        backgound.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 205, -1));

        jblPassword.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblPassword.setForeground(new java.awt.Color(51, 51, 51));
        jblPassword.setText("PASSWORD");
        backgound.add(jblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(204, 204, 204));
        txtUsuario.setText("Ingrese su usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuarioMousePressed(evt);
            }
        });
        backgound.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 420, 50));

        jblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jblUsuario.setForeground(new java.awt.Color(51, 51, 51));
        jblUsuario.setText("USUARIO");
        backgound.add(jblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        psdPassword.setBackground(new java.awt.Color(255, 255, 255));
        psdPassword.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        psdPassword.setForeground(new java.awt.Color(204, 204, 204));
        psdPassword.setText("**********");
        psdPassword.setBorder(null);
        psdPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                psdPasswordMousePressed(evt);
            }
        });
        psdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psdPasswordActionPerformed(evt);
            }
        });
        backgound.add(psdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 380, 60));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        backgound.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 530, 10));

        panelEntrar.setBackground(new java.awt.Color(92, 88, 29));

        jblEntrar.setBackground(new java.awt.Color(92, 88, 29));
        jblEntrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jblEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jblEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblEntrar.setText("ENTRAR");
        jblEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelEntrarLayout = new javax.swing.GroupLayout(panelEntrar);
        panelEntrar.setLayout(panelEntrarLayout);
        panelEntrarLayout.setHorizontalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEntrarLayout.setVerticalGroup(
            panelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backgound.add(panelEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 570, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        backgound.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 530, 10));

        jblIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        jblIniciarSesion.setForeground(new java.awt.Color(51, 51, 51));
        jblIniciarSesion.setText("INICIAR SESION");
        backgound.add(jblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        panelnAtras.setBackground(new java.awt.Color(255, 255, 255));

        jblAtras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        jblAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblAtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblAtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblAtrasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelnAtrasLayout = new javax.swing.GroupLayout(panelnAtras);
        panelnAtras.setLayout(panelnAtrasLayout);
        panelnAtrasLayout.setHorizontalGroup(
            panelnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelnAtrasLayout.setVerticalGroup(
            panelnAtrasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnAtrasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        backgound.add(panelnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelVerPassword.setBackground(new java.awt.Color(255, 255, 255));
        panelVerPassword.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblVerPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png"))); // NOI18N
        jblVerPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblVerPasswordMouseExited(evt);
            }
        });
        panelVerPassword.add(jblVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        backgound.add(panelVerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgound, javax.swing.GroupLayout.PREFERRED_SIZE, 668, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgoundFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_backgoundFocusGained
        //nada
    }//GEN-LAST:event_backgoundFocusGained

    private void jblAtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseExited
        panelnAtras.setBackground(Color.white);
    }//GEN-LAST:event_jblAtrasMouseExited

    private void jblAtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseEntered
        panelnAtras.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblAtrasMouseEntered

    private void jblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblAtrasMouseClicked
        this.dispose();
        Datos.getStart().setVisible(true);
    }//GEN-LAST:event_jblAtrasMouseClicked

    private void jblEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseExited
        panelEntrar.setBackground(new Color(92, 88, 29));
        jblEntrar.setForeground(Color.white);
    }//GEN-LAST:event_jblEntrarMouseExited

    private void jblEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseEntered
        panelEntrar.setBackground(new Color(153, 145, 86));
        jblEntrar.setForeground(Color.black);
    }//GEN-LAST:event_jblEntrarMouseEntered

    private void jblEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblEntrarMouseClicked
        String usuario = txtUsuario.getText();
        String password = psdPassword.getText();
        int PersonasRegistradas = Datos.listaPersonas.size();

        txtUsuario.setText("");
        psdPassword.setText("");

        boolean CredencialesIguales = false;
        int rol = 0;

        try {
            if (PersonasRegistradas > 0) {

                for (Personas p : Datos.listaPersonas) {
                    if (p.getNombre().equals(usuario) && p.getPassword().equals(password)) {
                        CredencialesIguales = true;
                        index = Datos.listaPersonas.indexOf(p);
                        Datos.setIndiceLogin(index);
                        rol = p.getRol();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "No hay usuarios registrados");
                txtsPorDefecto();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error, intentalo de nuevo");
            txtsPorDefecto();
        }

        if (CredencialesIguales == true) {
            JOptionPane.showMessageDialog(null, "Datos correctos");
            switch (rol) {
                case 0 -> {
                    Datos.setIndiceLogin(index);
                    this.dispose();
                    Administradores admins = new Administradores();
                    admins.setVisible(true);
                }
                case 1 -> {
                    Datos.setIndiceLogin(index);
                    this.dispose();
                    Administradores admins = new Administradores();
                    admins.setVisible(true);
                }
            }
        }else if (PersonasRegistradas > 0 && CredencialesIguales == false){
            JOptionPane.showMessageDialog(null, "Datos incorrectos");
            txtsPorDefecto();
        }
    }//GEN-LAST:event_jblEntrarMouseClicked

    private void psdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psdPasswordActionPerformed

    private void psdPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdPasswordMousePressed

        String user = txtUsuario.getText();
        if(String.valueOf(psdPassword.getPassword()).equals("**********")){
            psdPassword.setText("");
        }
        psdPassword.setForeground(Color.black);
        if(user.equals("")){
            txtUsuario.setText("Ingrese su usuario");
        }else{
            txtUsuario.setText(user);
        }
        txtUsuario.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_psdPasswordMousePressed

    private void txtUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMousePressed

        String psd = String.valueOf(psdPassword.getPassword());
        if(txtUsuario.getText().equals("Ingrese su usuario")){
            txtUsuario.setText("");
        }
        txtUsuario.setForeground(Color.black);
        if(psd.equals("")){
            psdPassword.setText("**********");
        }else{
            psdPassword.setText(psd);
        }
        psdPassword.setForeground(new Color(155, 155, 155));
    }//GEN-LAST:event_txtUsuarioMousePressed

    private void jblVerPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseEntered
        panelVerPassword.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jblVerPasswordMouseEntered

    private void jblVerPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseExited
        panelVerPassword.setBackground(Color.white);
    }//GEN-LAST:event_jblVerPasswordMouseExited

    private void jblVerPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblVerPasswordMouseClicked
        if (verPassword == false) {
            verPassword = true;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoAbierto.png")));
            psdPassword.setEchoChar((char) 0);
        } else {
            verPassword = false;
            jblVerPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ojoCerrado.png")));
            psdPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jblVerPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblAtras;
    private javax.swing.JLabel jblEntrar;
    private javax.swing.JLabel jblFondoPanel;
    private javax.swing.JLabel jblFrase;
    private javax.swing.JLabel jblIniciarSesion;
    private javax.swing.JLabel jblLogo;
    private javax.swing.JLabel jblNombreBanco;
    private javax.swing.JLabel jblPassword;
    private javax.swing.JLabel jblUsuario;
    private javax.swing.JLabel jblVerPassword;
    private javax.swing.JPanel panelEntrar;
    private javax.swing.JPanel panelVerPassword;
    private javax.swing.JPanel panelnAtras;
    private javax.swing.JPasswordField psdPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
